export const data_nonveg = [
  {
    id: 1,
    title: "Kadai Chicken",
    desc: "Kadai chicken originated from Northern region of India where the winter is quite strong which is why the North-Indian dishes are usually loaded with heat and flavors from all the aromatic spices or as they are called 'garam masala' i.e. 'hot spices'. Once a Nepali guy liked it so much that he requested the recipe for it. So I sent him the recipe and thus began my new friendship.",
    process: [
      "Cut the tomatoes. Crush garlic & ginger coarsely.",
      "Heat oil in the pan, saute some cloves, bay leaves, cinnamon, cumin seeds, green chillies.",
      "Add chicken & mix well. Now add green cardamom powder and black pepper. Mix well. After a few minutes add 1/2 cup of warm water. Then put the tomatoes on top & cover the pan. Cook for few minutes, till the tomatoes are pulpy.",
      "Remove the skin of the tomatoes & mash them. Add garlic, ginger and saute them for a few minutes.",
      "Now add garam masala powder, red chilli powder, turmeric powder, coriander powder & yogurt. Mix well. Now cover it again and let it boil for 2-3 minutes.",
      "Mix chopped coriender leaves and let it rest for about 5 minutes.",
      "Best served with Naan / Paratha.",
    ],
    ingridients: [
      "Chicken - 750gm",
      "Tomatoes - 4pc",
      "Garlic Cloves - 15-20",
      "Ginger - 1 inch",
      "Cloves - 3-4",
      "Bay Leaves - 2",
      "Cinnamon - 1 inch",
      "Cumin Seeds - 1 tbsp",
      "Chopped Green Chillies - 2-3",
      "Green Cardamom Powder - 1/4 tsp",
      "Oil - 4-5 tbsp",
      "Yogurt - 3/4 cup",
      "Red Chilli Powder - 1 tsp",
      "Turmeric Powder - 1/4 tsp",
      "Garam Masala - 1 tsp",
      "Chopped Fresh Coriander - 1/4 cup",
      "Black Pepper to taste",
      "Salt to taste",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/food-lab-pics/main/1.jpg",
  },

  {
    id: 4,
    title: "Chicken Fetucine Alfredo",
    desc: "Fettuccine Alfredo is an Italian pasta dish of fresh fettuccine tossed with butter and Parmesan cheese (Italian: pasta al burro e parmigiano). As the cheese melts, it emulsifies the liquids to form a smooth and rich cheese sauce coating the pasta. The dish is named after Alfredo Di Lelio, who featured the dish at his restaurant in Rome in the early to mid-20th century; the 'ceremony' of preparing it tableside was an integral part of the dish.",
    process: [
      "Set a pot of water to boil.",
      "Brush Chicken with olive oil and season with 1 tsp salt, pepper, garlic powder on both sides.",
      "On medium heat in a pan drizzle t tbsp of ooil and butter.",
      "Sear Chicken for 3-6 minutes on each side until golden brown.",
      "For the sauce melt 1/2 cup of butter.",
      "When butter is melted add 2 tbsp of cream cheese.",
      "When the mixture has softyen pour 1/2 cup heavy cream.",
      "Season with 1 tsp salt, pepper and garlic powder and simmer on low heat for 15 minutes.",
      "While sauce simmers add pasta and salt to boiling water.",
      "Remove sauce from heat stir and add parmesan cheese.",
      "Toss all ingredients well and serve.",
      "Garnish with some grated cheese and chopped parsley.",
    ],
    ingridients: [
      "Fettucine Pasta",
      "Chicken (cut into small pieces) - 200gm",
      "Butter - 2 tbsp",
      "Cheese",
      "Parmesan Cheese - 1 and a 1/2 cup",
      "Heavy Cream 2 cup",
      "Salt - 1 tsp",
      "Pepper - 1 tsp",
      "Garlic Powder - 2 tsp",
      "Milk - 3/4 cup",
      "Pasta Masala - 1 pinch",
      "Chilli Flakes - 1 pinch",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/food-lab-pics/main/4.jpg",
  },
];
