export const data_cake = [
  {
    id: 3,
    title: "Red Velvet Cake",
    desc: "In the 19th century, 'velvet' cake, a soft and velvety crumb cake, came to be served as a fancy dessert, in contrast to what had been the more common, coarser-crumbed cake. Around the turn of the 20th century, devil's food cake was introduced, which is how some believe that red velvet cake came about.",
    process: [
      "Start by beating butter & sugar in a bowl. Then add egg & beat. Add vanila essence & beat. Add curd & red food colour and beat.",
      "Add dry ingredients and mix by cut & fold method and bake for 35 mins at 180 deg (preheated oven)",
      "Mix cream cheese, powder suger & vanila essence - mix all togeather and wisk. Then mix 50 gr of whipped cream",
      "For the icing cream the soft cheese using a whisk. Then add sugar, vanilla extract and half of the whipped cream. Whisk them together. Now gently fold in the remaining whipped cream into the icing.",
      "Once the cake is completely cooled, using a bread knife to remove the top crust to flatten the cake. Also remove a thin layer from the sides. Reserve the bright crumbs for garnishing.",
      "Now using the bread knife slize the cake horizontally into 2 parts. Spread the icing evenly between the parts as well as on the side using a palette knife.",
      "Garnish the cake using the crumbs and let it chill for 2-3 hours before slicing it.",
      "Hence Sarmi's red velvet cake is done and dusted.",
    ],
    ingridients: [
      "BASE",
      "Maida -150 gr",
      "Cocoa Powder - 1 tbsp",
      "Baking Salt - 1 tsp",
      "Baking Powder- 1 tsp",
      "Salt -1 pinch",
      "Powdered Sugar -150 gr",
      "Butter -200 gr",
      "Egg- 2 pc",
      "Curd -125 gr",
      "FILLING",
      "Cream Cheese -250 gr",
      "Powdered Suger -70 gr",
      "Vanilla Essence - 1 tsp",
      "Whipped Cream(beated)",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/3.jpg",
  },

  {
    id: 5,
    title: "Red Velvet Cupcake",
    desc: "During WWII soldiers and civilians had to ration off food and supplies. Baking products like sugar and butter were a part of the rations. As a result, some bakers chose to use beet juice in their cakes.You can still find red velvet cake recipes today that call for beet juice. The red color of the beets makes the cake have a more delicious appeal. However, not only do the beets make the cake pretty, but they also make the cake soft.",
    process: [
      "Start off by preheating the oven to 160 °C (320°F) with the fan on. If your oven doesn't have a fan option, then you will need to increase the baking temperature to 175°C (347°F).",
      "Line up the cupcake tray with cupcake liners",
      "For our cupcakes start off by putting 1¼ cupsof all purpose flour, 1½ tbsp cornflour, 1½ tbsp cocoa powder, ¼ tsp baking soda, ½ tsp baking powder, ¼ tsp salt. Use a whisk to combine them together.",
      "Set this aside and on another bowl add 3tbsp of unsalted butter, ⅓ cup vegetable oil, 1 cup white sugar. Using the blender blend all of the ingredients together until its light and creamy. Then add 2 eggs one at atime mixing well in between each addition.",
      "Then add ½ tbsp vanilla essence/extract, ¾ tsp white vinegar, 1¾ tbsp red liquid food colour. Then add the dry ingredients from the other bowl and add ⅓ cup buttermilk and mix them together",
      "Distribute it evenly in the cupcake tray and bake them until fluffy",
      "For the cheese frosting add ½ cup of unsalted butter, 2¼ cups icing sugar in 2-3 batches, ¾ cup cream cheese, ¾ tsp vanilla essence/extract, ¾ tbsp lemon juice and mix them.",
      "Now use this frosting to swirl around thew cupcake. So, we have ourselves Sarmi's style red velvet cupcakes.",
    ],
    ingridients: [
      "1¼ cups regular all-purpose flour",
      "1½ tbsp cornflour",
      "1½ tbsp unsweetened cocoa powder",
      "¼ tsp baking soda",
      "½ tsp baking powder",
      "¼ tsp salt - omit if using salted butter",
      "3 tbsp unsalted butter",
      "⅓ cup unflavoured vegetable oil",
      "1 cup white sugar",
      "2 large eggs - room temperature",
      "½ tbsp vanilla essence/extract",
      "¾ tsp white vinegar",
      "1¾ tbsp red liquid food colour",
      "⅓ cup buttermilk",
      "-- Cream Cheese Buttercream --",
      "½ cup unsalted butter",
      "2¼ cups icing sugar",
      "¾ cup cream cheese",
      "¾ tsp vanilla essence/extract",
      "¾ tbsp lemon juice",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/5.jpg",
  },

  {
    id: 3,
    title: "Food test",
    desc: "lorem safasf safsafsafsaf f af safas ac asc c ac asc",
    process: ["Step 1", "Step 2"],
    ingridients: ["Step 1", "Step 2"],
    image:
      "https://plus.unsplash.com/premium_photo-1663844169693-9b0eb5032423?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw3fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60",
  },
];
