export const data = [
  {
    id: 1,
    title: "Kadai Chicken",
    desc: "Kadai chicken originated from Northern region of India where the winter is quite strong which is why the North-Indian dishes are usually loaded with heat and flavors from all the aromatic spices or as they are called 'garam masala' i.e. 'hot spices'. Once a Nepali guy liked it so much that he requested the recipe for it. So I sent him the recipe and thus began my new friendship.",
    process: [
      "Cut the tomatoes. Crush garlic & ginger coarsely.",
      "Heat oil in the pan, saute some cloves, bay leaves, cinnamon, cumin seeds, green chillies.",
      "Add chicken & mix well. Now add green cardamom powder and black pepper. Mix well. After a few minutes add 1/2 cup of warm water. Then put the tomatoes on top & cover the pan. Cook for few minutes, till the tomatoes are pulpy.",
      "Remove the skin of the tomatoes & mash them. Add garlic, ginger and saute them for a few minutes.",
      "Now add garam masala powder, red chilli powder, turmeric powder, coriander powder & yogurt. Mix well. Now cover it again and let it boil for 2-3 minutes.",
      "Mix chopped coriender leaves and let it rest for about 5 minutes.",
      "Best served with Naan / Paratha.",
    ],
    ingridients: [
      "Chicken - 750gm",
      "Tomatoes - 4pc",
      "Garlic Cloves - 15-20",
      "Ginger - 1 inch",
      "Cloves - 3-4",
      "Bay Leaves - 2",
      "Cinnamon - 1 inch",
      "Cumin Seeds - 1 tbsp",
      "Chopped Green Chillies - 2-3",
      "Green Cardamom Powder - 1/4 tsp",
      "Oil - 4-5 tbsp",
      "Yogurt - 3/4 cup",
      "Red Chilli Powder - 1 tsp",
      "Turmeric Powder - 1/4 tsp",
      "Garam Masala - 1 tsp",
      "Chopped Fresh Coriander - 1/4 cup",
      "Black Pepper to taste",
      "Salt to taste",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/1.jpg",
  },

  {
    id: 2,
    title: "Mango Peda",
    desc: "'Mango Peda', a flavorful and delicious Indian sweet / dessert. The mango mania now continues with one more Indian dessert rich with the flavor of mangoes. This time around it is in the form of a Mango Peda, which is sweet, chewy and yet dissolves in your mouth just like a good old Indian sweet.",
    process: [
      "firstly, in a large kadai heat 2 tbsp ghee, ¼ cup milk, few thread saffron and 1 cup mango pulp.",
      "stir well making sure everything is well combined.",
      "now add ¼ cup sugar and stir until sugar dissolves completely.",
      "further, add 1 cup milk powder and ¼ cup cashew powder.",
      "mix well making sure the mixture is well combined.",
      "mash well making sure there are no lumps present.",
      "keeping the flame on low, stir continuously. the mixture thickens after 5 minutes.",
      "further, add ¼ tsp cardamom powder and mix well.",
      "and after 15 minutes, the mixture starts to separate the pan and holds shape. do not overcook as the peda hardens.",
      "transfer the prepared mixture into a greased plate and spread uniformly.",
      "cool for 5 minutes, and start preparing ball-sized peda.",
      "design using the flower mould. you can also decorate using a toothpick or fork.",
      "finally, serve mango peda for a week when stored in an airtight container.",
    ],
    ingridients: [
      "2 tbsp ghee / clarified butter",
      "¼ cup milk",
      "few thread saffron / kesar",
      "1 cup mango pulp",
      "¼ cup sugar",
      "1 cup milk powder (unsweetened)",
      "¼ cup cashew powder",
      "¼ tsp cardamom powder",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/2.jpg",
  },

  {
    id: 3,
    title: "Red Velvet Cake",
    desc: "In the 19th century, 'velvet' cake, a soft and velvety crumb cake, came to be served as a fancy dessert, in contrast to what had been the more common, coarser-crumbed cake. Around the turn of the 20th century, devil's food cake was introduced, which is how some believe that red velvet cake came about.",
    process: [
      "Start by beating butter & sugar in a bowl. Then add egg & beat. Add vanila essence & beat. Add curd & red food colour and beat.",
      "Add dry ingredients and mix by cut & fold method and bake for 35 mins at 180 deg (preheated oven)",
      "Mix cream cheese, powder suger & vanila essence - mix all togeather and wisk. Then mix 50 gr of whipped cream",
      "For the icing cream the soft cheese using a whisk. Then add sugar, vanilla extract and half of the whipped cream. Whisk them together. Now gently fold in the remaining whipped cream into the icing.",
      "Once the cake is completely cooled, using a bread knife to remove the top crust to flatten the cake. Also remove a thin layer from the sides. Reserve the bright crumbs for garnishing.",
      "Now using the bread knife slize the cake horizontally into 2 parts. Spread the icing evenly between the parts as well as on the side using a palette knife.",
      "Garnish the cake using the crumbs and let it chill for 2-3 hours before slicing it.",
      "Hence Sarmi's red velvet cake is done and dusted.",
    ],
    ingridients: [
      "BASE",
      "Maida -150 gr",
      "Cocoa Powder - 1 tbsp",
      "Baking Salt - 1 tsp",
      "Baking Powder- 1 tsp",
      "Salt -1 pinch",
      "Powdered Sugar -150 gr",
      "Butter -200 gr",
      "Egg- 2 pc",
      "Curd -125 gr",
      "FILLING",
      "Cream Cheese -250 gr",
      "Powdered Suger -70 gr",
      "Vanilla Essence - 1 tsp",
      "Whipped Cream(beated)",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/3.jpg",
  },

  {
    id: 4,
    title: "Chicken Fetucine Alfredo",
    desc: "Fettuccine Alfredo is an Italian pasta dish of fresh fettuccine tossed with butter and Parmesan cheese (Italian: pasta al burro e parmigiano). As the cheese melts, it emulsifies the liquids to form a smooth and rich cheese sauce coating the pasta. The dish is named after Alfredo Di Lelio, who featured the dish at his restaurant in Rome in the early to mid-20th century; the 'ceremony' of preparing it tableside was an integral part of the dish.",
    process: [
      "Set a pot of water to boil.",
      "Brush Chicken with olive oil and season with 1 tsp salt, pepper, garlic powder on both sides.",
      "On medium heat in a pan drizzle t tbsp of ooil and butter.",
      "Sear Chicken for 3-6 minutes on each side until golden brown.",
      "For the sauce melt 1/2 cup of butter.",
      "When butter is melted add 2 tbsp of cream cheese.",
      "When the mixture has softyen pour 1/2 cup heavy cream.",
      "Season with 1 tsp salt, pepper and garlic powder and simmer on low heat for 15 minutes.",
      "While sauce simmers add pasta and salt to boiling water.",
      "Remove sauce from heat stir and add parmesan cheese.",
      "Toss all ingredients well and serve.",
      "Garnish with some grated cheese and chopped parsley.",
    ],
    ingridients: [
      "Fettucine Pasta",
      "Chicken (cut into small pieces) - 200gm",
      "Butter - 2 tbsp",
      "Cheese",
      "Parmesan Cheese - 1 and a 1/2 cup",
      "Heavy Cream 2 cup",
      "Salt - 1 tsp",
      "Pepper - 1 tsp",
      "Garlic Powder - 2 tsp",
      "Milk - 3/4 cup",
      "Pasta Masala - 1 pinch",
      "Chilli Flakes - 1 pinch",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/4.jpg",
  },

  {
    id: 5,
    title: "Red Velvet Cupcake",
    desc: "During WWII soldiers and civilians had to ration off food and supplies. Baking products like sugar and butter were a part of the rations. As a result, some bakers chose to use beet juice in their cakes.You can still find red velvet cake recipes today that call for beet juice. The red color of the beets makes the cake have a more delicious appeal. However, not only do the beets make the cake pretty, but they also make the cake soft.",
    process: [
      "Start off by preheating the oven to 160 °C (320°F) with the fan on. If your oven doesn't have a fan option, then you will need to increase the baking temperature to 175°C (347°F).",
      "Line up the cupcake tray with cupcake liners",
      "For our cupcakes start off by putting 1¼ cupsof all purpose flour, 1½ tbsp cornflour, 1½ tbsp cocoa powder, ¼ tsp baking soda, ½ tsp baking powder, ¼ tsp salt. Use a whisk to combine them together.",
      "Set this aside and on another bowl add 3tbsp of unsalted butter, ⅓ cup vegetable oil, 1 cup white sugar. Using the blender blend all of the ingredients together until its light and creamy. Then add 2 eggs one at atime mixing well in between each addition.",
      "Then add ½ tbsp vanilla essence/extract, ¾ tsp white vinegar, 1¾ tbsp red liquid food colour. Then add the dry ingredients from the other bowl and add ⅓ cup buttermilk and mix them together",
      "Distribute it evenly in the cupcake tray and bake them until fluffy",
      "For the cheese frosting add ½ cup of unsalted butter, 2¼ cups icing sugar in 2-3 batches, ¾ cup cream cheese, ¾ tsp vanilla essence/extract, ¾ tbsp lemon juice and mix them.",
      "Now use this frosting to swirl around thew cupcake. So, we have ourselves Sarmi's style red velvet cupcakes.",
    ],
    ingridients: [
      "1¼ cups regular all-purpose flour",
      "1½ tbsp cornflour",
      "1½ tbsp unsweetened cocoa powder",
      "¼ tsp baking soda",
      "½ tsp baking powder",
      "¼ tsp salt - omit if using salted butter",
      "3 tbsp unsalted butter",
      "⅓ cup unflavoured vegetable oil",
      "1 cup white sugar",
      "2 large eggs - room temperature",
      "½ tbsp vanilla essence/extract",
      "¾ tsp white vinegar",
      "1¾ tbsp red liquid food colour",
      "⅓ cup buttermilk",
      "-- Cream Cheese Buttercream --",
      "½ cup unsalted butter",
      "2¼ cups icing sugar",
      "¾ cup cream cheese",
      "¾ tsp vanilla essence/extract",
      "¾ tbsp lemon juice",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/5.jpg",
  },

  {
    id: 6,
    title: "Tandoori Chicken",
    desc: "Dishes similar to tandoori chicken may have existed during the Harappan civilization during the Bronze Age of India. According to the archeologist Professor Vasant Shinde, the earliest evidence for a dish similar to tandoori chicken can be found in the Harappan civilization and dates back to 3000 BC. His team has found ancient ovens at Harappan sites which are similar to the tandoors that are used in the state of Punjab.",
    process: [
      "Make ½ cm deep cuts in the chicken surface. ",
      "Rub with 1 tsp salt, 1 tbsp lemon juice and 1 tsp red chili powder and set aside for 20 minutes.",
      "      Meanwhile heat mustard oil till lukewarm.",
      " Add the remaining red chili powder and blend well. Add all the remaining ingredients and mix well. You may add red colour or not, it is optional.",
      "Squeeze out all the moisture from the chicken and rub well with the prepared marinade.",
      "Marinate the chicken for 6-7 hours in the refrigerator.",
      "Remove the chicken from the refrigerator. Keep a live burning coal in a bowl and keep it in the middle of the chicken. Pour 1 tbsp mustard oil over it and cover immediately. Secure tightly so that no smoke escapes. Allow the smoke to settle down and rest for 15 minutes.",
      "Heat a large pan till very hot. Keep the chicken pieces over it and sear the chicken. When it colours on the underside, flip and cook on the other side too.",
      "Place a wire grill over the gas stove flame and place the cooked chicken pieces over it. Allow to char a bit. Baste with melted butter and flip. Cook till the chicken is done. Remove and serve with chutney, lemon wedges and onion rings.",
    ],
    ingridients: [
      "800g Chicken",
      "250 ml hung yoghurt",
      "1 tsp roasted cumin powder",
      "1 tbsp garlic paste",
      "1 tbsp ginger paste",
      "2 tbsp mustard (sarson) oil",
      "2 tbsp fresh lime juice",
      "Salt to taste",
      "¼ tsp turmeric powder",
      "1 tsp garam masala",
      "1 tsp black pepper",
      "1 tsp finely chopped green chilies",
      "2 tbsp Kashmiri red chili powder",
      "Butter to baste",
      "a pinch of orange red (tandoori) colour",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/6.jpg",
  },

  {
    id: 7,
    title: "Mocha Chingri",
    desc: "This Bengali delicacy makes use of a marvelous vegetable - the banana flower, known as 'mocha' in Bengali. Cooked with shrimps and coconut, it is best served with rice on the side.",
    process: [
      "Soak the chopped banana blossom in salted water along with a pinch of turmeric powder and juice of 1/2 lime for an hour.",
      "Marinate the prawns with a pinch of salt, turmeric powder and red chilli powder for 10 minutes.",
      "Wash the soaked banana blossom well and drain. Pressure cook in required quantity of water in which a pinch each of salt and turmeric powder has been added. Drain and mash well. Keep aside.",
      "Heat oil in a pan and fry the potatoes till light brown. Drain and keep aside. Fry the marinated prawns till they changes colour and keep aside.",
      "Temper the same oil with dry red chilies, bay leaves, cumin seeds, cinnamon, cloves and cardamoms.",
      "Add the onion and saute till light brown.",
      "Then add the ginger-garlic paste & all the dry spices (except garam masala and salt) mixed with some water. Saute till the oil separates.",
      "Add the chopped tomatoes and stir fry till it is mashed.",
      "Add the fried potatoes & prawns. Mix nicely and cook on a low flame for 2-3 minutes.",
      "Add the boiled mocha (banana flower), salt & green chilies. Give it a stir and cook, covered on a low flame till done. Sprinkle water at intervals if needed.",
      "When done, add the garam masala & ghee. Give it a toss and switch off the flame.",
      "Serve with hot steamed rice or chapati.",
    ],
    ingridients: [
      "1 medium size mocha / banana blossom, cleaned & chopped finely",
      "10-15 prawns, deveined & washed",
      "3 tbsp mustard oil",
      "2 bay leaves",
      "2 whole dry red chilies",
      "1 cinnamon stick",
      "2-3 green cardamoms",
      "4-5 cloves",
      "1 tsp cumin seeds",
      "1 potato, cubed",
      "1 onion, chopped",
      "1 tsp ginger-garlic paste",
      "1 tomato, chopped",
      "2-3 green chilies, slit to taste salt",
      "1/2 tsp turmeric powder",
      "1 tsp sugar (opt)",
      "1 tbsp coriander-cumin powder",
      "1 tsp garam masala powder",
      "1 tsp ghee",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/7.jpg",
  },

  {
    id: 8,
    title: "Chicken Biryani",
    desc: " Indian restaurateur Kris Dhillon believes that the dish originated in Persia, and was brought to India by the Mughals. Another theory claims that the dish was prepared in India before the first Mughal emperor Babur conquered India.",
    process: [
      "Powder the special garam masala powde",
      "Start by marinating the chicken with all the ingredients given. Let it marinate for 2 hours but overnight is grea",
      "Wash and soak basmati rice for a hou",
      "      Bring lots of water with salt to a boil. Once it boils, add in the drained rice and cook it for 5 to 7 mins till it is 90 percent done. When you taste it, it should have a bite.Drain it and set asid",
      "      Heat oil in a big pot which you are making biryan",
      "      Add in onions and fry till golden, drain and set asid",
      "      Soak saffron in some warm milk, heat ghee in a sauce pan and fry cashews and raisans till golde",
      "      In the same oil add in chicken and mix well for 5 min",
      "      Now layer the rice over it, top with fried onions, chopped herbs, saffron milk, fried nuts along with the ghee, kewra and rose essence. Cover the entire pot with foil and cover with a plate. Place a weight over it and let it cook on a very very low flame for 30 to 35 min",
      "      Now remove the weight and foil and fluff the rice carefull",
      "      Serve wih some raita.",
    ],
    ingridients: [
      "1 kg Basmati Rice",
      "¾ cup Oil",
      "1.5 kg Chicken",
      "3 large Onion sliced thinly",
      "a pinch Saffron a pinch",
      "¼ cup Warm Milk",
      "¼ cup Coriander leaves finely chopped",
      "¼ cup Mint Leaves finely chopped",
      "3 tbsp Ghee",
      "50 grams Cashews",
      "50 grams Kishmish",
      "Kewra Essence few drops",
      "Rose Essence few drops",
      "Salt to taste",
      "or Marination",
      "2 tbsp Chilli Powder",
      "3 tbsp Coriander Powder",
      "Salt to taste",
      "½ cup Coriander leaves chopped finely",
      "½ cup Mint Leaves chopped finely",
      "1½ cup Thick Unsour Curd",
      "4 Green Chillies",
      "3 tbsp Ginger Garlic Paste - 3 tblspn",
      "Special Garam Masala Powder (recipe below)",
      "1 tbsp Lemon Juice",
      "or Special Garam Masala Powder:",
      "10 piece Cloves",
      "10 piece Cardamom",
      "3 Bay Leaf",
      "5cm Cinnamon",
      "1 tbsp Cumin Seeds",
      "4 Black Stone Flower / Kal Paasi",
      "1 Star Anise",
      "1 tbsp Fennel Seeds",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/8.jpg",
  },

  {
    id: 9,
    title: "Beetroot Raita",
    desc: "Raita is a side dish in Indian cuisine made of dahi (yogurt, often referred to as curd) together with raw or cooked vegetables, more seldom fruit, or in the case of boondi raita, with fried droplets of batter made from besan (chickpea flour, generally labeled as gram flour).",
    process: [
      "Take some curd in a bowl.",
      "Add half-boiled beetroot to it.",
      "Add boiled sweetcorn to it.",
      "Blend them well together.",
      "Now, pour it in a bowl and add chopped cucumber.",
      "Add salt and stir well.",
      "Garnish with pudina leaves, chilli flakes and some sweetcorn.",
      "Best paired with Biryani or some other dishes.",
    ],
    ingridients: [
      "2 Cups Curd",
      "3 tsp Half-Boiled Beetroot",
      "1 tsp Cucumber",
      "1/2 small Onion",
      "1/2 tsp Salt",
      "2 tsp Coriander Leaves",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/9.jpg",
  },

  {
    id: 10,
    title: "Shukto",
    desc: "A common misconception about Bengalis is that their love for food is only limited to all things sweet or meat and fish-based. It’s true that their overwhelming obsession with ilish mach, mangsho, chingri and roshogollas have led to this stereotype, but there exists an underrated vegetarian culinary star in Bengali cuisine that is replete with subtle flavours and interesting twists — the hallowed ‘Shukto’.",
    process: [
      "Cut potatoes and sweet potatoes length-wise, into 2-cm wide wedges. Cut kachkola, pepe and brinjal into 6-cm long, 3-cm wide pieces. Trim the ends of sheem, remove the fibrous strands, and halve them. Chop korola into 4-cm long slices. Strip off the the outer fibres of shojne data (drumstick), and divide them in 5-cm long sections.",
      "The vegetables will be prepped in two ways before we start cooking: (a) shojne data, pepe, sheem, sweet potato, and potato will need to be parboiled, and (b) brinjal, kachkola, and korola will need to be fried.",
      "So, put the first group of vegetables in a boiling pot with 5 g salt and 600 g water. Put the lid on and parboil on low heat for 15 minutes. Stir midway to steam evenly. When done, strain immediately to prevent the vegetables from cooking further. While straining, reserve the water for later use.",
      "Heat vegetable oil in a kadai. Fry daal'er bori until golden. Set aside. Similarly, fry korola, kachkola and brinjal one after the other, until each one is golden. Remove from the oil and set aside.",
      "Temper the oil with bay leaves and paanch phoron. Once aromatic, add ginger paste and fry it on low heat for a minute. Then add shorshe bata (mustard paste) and continue frying. If pan dries out, add a splash of water (you can use the water you reserved earlier while straining the vegetables). Stir well until oil separates.",
      "Add boiled potatoes, and cook on low heat for 3 minutes. Add the rest of the boiled vegetables, along with fried kachkola and the bori. Add 15 g salt and 22 g sugar. Mix everything well.",
      "Sprinkle grated coconut and give everything a gentle stir. Now, add the water reserved from the boiled vegetables. Add brinjal and korola. Mix gently so that the veggies don't break.",
      "Make a solution of milk and maida, and pour it into the pan. Allow everything to bubble on low heat until all the vegetables are fully cooked (around 3 to 5 minutes).",
      "To finish, crush radhuni to a powder using a mortar and pestle, and sprinkle it over the shukto. Finally, add ghee, cover the pan, and allow it to rest for a minute or so, before searving.",
    ],
    ingridients: [
      "160 g shojne data (drumsticks)",
      "120 g mishti alu (sweet potato)",
      "100 g sheem (flat beans)",
      "100 g brinjal",
      "50 g korola (bitter gourd)",
      "100 g potato",
      "150 g kachkola (unripe bananas)",
      "150 g kacha pepe (unripe papaya)",
      "10 pcs dal'er bori (sundried lentil dumplings)",
      "600 g water",
      "60 g vegetable oil",
      "4 pcs bay leaves",
      "½ tsp paanch phoron",
      "35 g ginger paste",
      "25 g sorshe bata (fresh ground mustard paste)",
      "15 g coconut (grated)",
      "‍100 g milk",
      "‍¼ tsp maida‍",
      "20 g total salt‍",
      "22 g sugar‍",
      "½ tsp radhuni (finely ground)‍",
      "10 g ghee",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/10.jpg",
  },

  {
    id: 11,
    title: "White Choco Cubes",
    desc: "The creation of the first modern chocolate bar is credited to Joseph Fry, who in 1847 discovered that he could make a moldable chocolate paste by adding melted cacao butter back into Dutch cocoa. By 1868, a little company called Cadbury was marketing boxes of chocolate candies in England.",
    process: [
      "First take the White Chocolate(crushed) into a bowl and microwave for 30 secs. After 30 secs take it out and stir with a dry spoon. Then again microwave for 30secs. After that add 1/2tsp of butter and mix it well.",
      "Rest for the chocolate compound for 4 mins in room temperature. Mix some pesta as well.",
      "Add the white chocolate in the mold and freeze for 2 mins.",
      "Now your cute little White Choco Cubes is ready to be served.",
    ],
    ingridients: [
      "200gm White Chocolate Compound",
      "1/2tsp Unsalted Butter",
      "Few crushed pesta",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/11.jpg",
  },

  {
    id: 12,
    title: "Mango Ice-cream",
    desc: "Raita is aIce cream is a frozen dessert typically made from milk or cream that has been flavoured with a sweetener, either sugar or an alternative, and a spice, such as cocoa or vanilla, or with fruit, such as mangoes, strawberries or peaches. Food colouring is sometimes added in addition to stabilizers. side dish in Indian cuisine made of dahi (yogurt, often referred to as curd) together with raw or cooked vegetables, more seldom fruit, or in the case of boondi raita, with fried droplets of batter made from besan (chickpea flour, generally labeled as gram flour).",
    process: [
      "To a mixer jar add mango flesh from 3-4 small alphonso mangoes.",
      "Blend it to a puree without adding water.",
      "Measure 2 cups of this mango pulp and transfer to a container.",
      "Add 1 cup sweetened condensed milk to it.",
      "Use a whisk and whisk well, should be well blended.",
      "The mixture will be slightly thick and creamy.",
      "To another mixing bowl add 1 cup frozen whipping cream.",
      "Start whipping using a hand blender. Use handwhisk too but it will take some time to whip else use a mixer jar with whipper blade.",
      "Keep whipping in medium speed until you start to see the cream turning foamy like this.",
      "Mildy stiff peaks is enough just as it is shown here in the below picture.",
      "Now add mango condensed milk mixture.",
      "Fold in gently.",
      "Mix until well combined.",
      "Pour into freezer safe containers. I used a regular plastic box with lid and my bread loaf tin.",
      "Place a butter paper over it, close with lid and freeze it for minimum 8 hrs.",
      "Now after 12 hrs remove the containers from fridge, rest for 5 mins atleast then remove the butter paper.",
      "Dip the icecream scooper in warm water.",
      "Then start scooping. If it is too hard wait for 2 more mins then scoop.",
      "First it may feel hard later after starting to scoop you will feel the creaminess.",
      "Yummy Mango Ice Cream is ready.",
    ],
    ingridients: [
      "2 Cups Curd",
      "3 tsp Boiled Beetroot",
      "1 tsp Cucumber",
      "1/2 small Onion",
      "1/2 tsp Salt",
      "2 tsp Coriander Leaves",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/12.jpg",
  },

  {
    id: 16,
    title: "Double Choco Modak",
    desc: "The origin of Modak is thought to have originated in the state of Maharashtra. Modak is known by many names throughout Indiaviz…mothagam or kozhukattai in Tamil, modhaka or kadubu in Kannada, and kudumu in Telugu, state-wise. In Japan, kangidan, a sweet similar to Modak, is presented to God Kangiten, the Japanese equivalent of Lord Ganesh. Kangidans are a type of dessert made with curds, honey, and red bean paste. They are deep fried after being wrapped in kneaded dough made from parched flour and shaped like a bun.",
    process: [
      "First take the Dark Chocolate(crushed) into a bowl and microwave for 30 secs. After 30 secs take it out and stir with a dry spoon. Then again microwave for 30secs. After that add 1/2tsp of butter and mix it well.",
      "Repeat the same process for white chocolate. After microwaving add some cashew nuts and pesta in the white chocolate and mix it well.",
      "Rest for the chocolate compound for 4 mins in room temperature.",
      "Add the white chocolate in the mold(modak mold) and cover it upto 1/3rd of the mold. Freeze for 2 mins and then add the dark chocolate upto the remaining height in the mold and freeze for another 2 mins.",
      "Now your Double Choco Modak is ready to be served.",
    ],
    ingridients: [
      "200gm White Chocolate",
      "100gm Dark Chocolate",
      "50gm Cashew Nuts (Grounded)",
      "50gm Pesta",
      "1tsp Unsalted Butter",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/16.jpg",
  },

  {
    id: 17,
    title: "Mango Kesari Phirni",
    desc: "Despite the dearth of evidence, it is believed that phirni hailed from ancient Persia or Middle East and it’s the Mughals who both invented and introduced it to India. The Mughal Empire relished the regal milk-based dish and made it popular. It is also backed by studies which say that the rich, milky, nutty and aromatic rice pudding in earthen bowls is a Mughal legacy. It was found that in Persia where Phirini is believed to have originated used the creamy rice pudding as the food of angels and was known as Sheer Birinj. It was first offered to Prophet Muhammad when he soared to 7th floor of heaven to meet God.",
    process: [
      "Firstly, soak 2 tbsp of basmati rice for 30 minutes.",
      "Discard the water and blend rice to coarse paste. Keep aside.",
      "Now in a large kadai boil 1 litre milk.",
      "Stir occasionally, and simmer for 10 minutes.",
      "Keep the flame on low or till milk thickens.",
      "Now add in prepared coarse rice paste.",
      "Stir continuously for 5 minutes else, lumps might form.",
      "Simmer for another 5 minutes stirring in between.",
      "Boil the milk till the rice gets cooked completely.",
      "Further add ¼ cup of sugar and 2 tbsp saffron milk.",
      "Mix well till the milk thickens and turn creamy.",
      "Add in cardamom powder and serve chilled garnished with chopped nuts.",
      "If looking to prepare mango phirni, allow the phirni to cool completely.",
      "Now add in ½ cup mango pulp and mix well. add more pulp depending on the sweetness.",
      "Finally, serve chilled mango phirni garnished with mango pulp, few chopped nuts, kesar and dry rose petals",
      "Delicious Mango kesari Phirni is ready to be served.",
    ],
    ingridients: [
      "2 tbsp basmati rice",
      "Water for soaking",
      "1 litre milk (full cream)",
      "¼ cup sugar",
      "¼ tsp cardamom powder / elachi powder",
      "2 tbsp saffron milk",
      "1 cup mango pulp",
      "Kesar, pesta(chopped)",
      "Rose Petals for garnishing.",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/17.jpg",
  },

  {
    id: 18,
    title: "Sujir Mohanbhog",
    desc: " Earlier according to some scholars, this dish was introduced to India by the Mughals, but the theory was discredited as it was already listed as shali-anna, present-day Kesari bat, in Manasollasa, a 12th-century work by a south Indian Chalukyan king, Someshvara III. In 14th-century Spain, semolina was cooked with almond milk, oil and optionally saffron for coloring. In India, sheera is made from semolina, ghee, and sugar; cardamom and milk, almonds and cashew-nuts are added.",
    process: [
      "In a pan mix together water, cardamom and sugar. Bring to a boil and stir till the sugar dissolves. Turn off the heat and keep.",
      "In a separate pan heat ghee and add suji. Cook on low heat till golden brown. Add the sugar syrup to the suji. Be careful as the suji will let off a lot of heat & steam when you add the syrup. Stir and cook the suji on medium heat till it thickens.",
      "Garnish with some grounded cashew nuts, dry rose petals and pesta",
      "Serve hot or cold as per your choice.",
    ],
    ingridients: [
      "Ghee – ⅔ cup",
      "Suji (semolina) – 1cup",
      "Water – 3cups",
      "Cardamom – 5no",
      "Sugar – ¾ cup",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/18.jpg",
  },
];
