export const data_dessert = [
  {
    id: 2,
    title: "Mango Peda",
    desc: "'Mango Peda', a flavorful and delicious Indian sweet / dessert. The mango mania now continues with one more Indian dessert rich with the flavor of mangoes. This time around it is in the form of a Mango Peda, which is sweet, chewy and yet dissolves in your mouth just like a good old Indian sweet.",
    process: [
      "firstly, in a large kadai heat 2 tbsp ghee, ¼ cup milk, few thread saffron and 1 cup mango pulp.",
      "stir well making sure everything is well combined.",
      "now add ¼ cup sugar and stir until sugar dissolves completely.",
      "further, add 1 cup milk powder and ¼ cup cashew powder.",
      "mix well making sure the mixture is well combined.",
      "mash well making sure there are no lumps present.",
      "keeping the flame on low, stir continuously. the mixture thickens after 5 minutes.",
      "further, add ¼ tsp cardamom powder and mix well.",
      "and after 15 minutes, the mixture starts to separate the pan and holds shape. do not overcook as the peda hardens.",
      "transfer the prepared mixture into a greased plate and spread uniformly.",
      "cool for 5 minutes, and start preparing ball-sized peda.",
      "design using the flower mould. you can also decorate using a toothpick or fork.",
      "finally, serve mango peda for a week when stored in an airtight container.",
    ],
    ingridients: [
      "2 tbsp ghee / clarified butter",
      "¼ cup milk",
      "few thread saffron / kesar",
      "1 cup mango pulp",
      "¼ cup sugar",
      "1 cup milk powder (unsweetened)",
      "¼ cup cashew powder",
      "¼ tsp cardamom powder",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/2.jpg",
  },

  {
    id: 9,
    title: "Beetroot Raita",
    desc: "Raita is a side dish in Indian cuisine made of dahi (yogurt, often referred to as curd) together with raw or cooked vegetables, more seldom fruit, or in the case of boondi raita, with fried droplets of batter made from besan (chickpea flour, generally labeled as gram flour).",
    process: [
      "Take some curd in a bowl.",
      "Add boiled beetroot to it.",
      "Blend them well together.",
      "Now, pour it in a bowl and add chopped cucumber and finely cut onions on top of it.",
      "Add salt and stir well.",
      "Garnish with coriander leaves.",
      "Best paired with Biryani or some other dishes.",
    ],
    ingridients: [
      "2 Cups Curd",
      "3 tsp Boiled Beetroot",
      "1 tsp Cucumber",
      "1/2 small Onion",
      "1/2 tsp Salt",
      "2 tsp Coriander Leaves",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/9.jpg",
  },

  {
    id: 11,
    title: "White Choco Cubes",
    desc: "Raita is aIce cream is a frozen dessert typically made from milk or cream that has been flavoured with a sweetener, either sugar or an alternative, and a spice, such as cocoa or vanilla, or with fruit, such as mangoes, strawberries or peaches. Food colouring is sometimes added in addition to stabilizers. side dish in Indian cuisine made of dahi (yogurt, often referred to as curd) together with raw or cooked vegetables, more seldom fruit, or in the case of boondi raita, with fried droplets of batter made from besan (chickpea flour, generally labeled as gram flour).",
    process: [
      "To a mixer jar add mango flesh from 3-4 small alphonso mangoes.",
      "Blend it to a puree without adding water.",
      "Measure 2 cups of this mango pulp and transfer to a container.",
      "Add 1 cup sweetened condensed milk to it.",
      "Use a whisk and whisk well, should be well blended.",
      "The mixture will be slightly thick and creamy.",
      "To another mixing bowl add 1 cup frozen whipping cream.",
      "Start whipping using a hand blender. Use handwhisk too but it will take some time to whip else use a mixer jar with whipper blade.",
      "Keep whipping in medium speed until you start to see the cream turning foamy like this.",
      "Mildy stiff peaks is enough just as it is shown here in the below picture.",
      "Now add mango condensed milk mixture.",
      "Fold in gently.",
      "Mix until well combined.",
      "Pour into freezer safe containers. I used a regular plastic box with lid and my bread loaf tin.",
      "Place a butter paper over it, close with lid and freeze it for minimum 8 hrs.",
      "Now after 8 hrs remove the containers from fridge, rest for 5 mins atleast then remove the butter paper.",
      "Dip the icecream scooper in warm water.",
      "Then start scooping. If it is too hard wait for 2 more mins then scoop.",
      "First it may feel hard later after starting to scoop you will feel the creaminess.",
      "Yummy Mango Ice Cream is ready.",
    ],
    ingridients: [
      "2 Cups Curd",
      "3 tsp Boiled Beetroot",
      "1 tsp Cucumber",
      "1/2 small Onion",
      "1/2 tsp Salt",
      "2 tsp Coriander Leaves",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/11.jpg",
  },

  {
    id: 12,
    title: "Mango Ice-cream",
    desc: "Raita is aIce cream is a frozen dessert typically made from milk or cream that has been flavoured with a sweetener, either sugar or an alternative, and a spice, such as cocoa or vanilla, or with fruit, such as mangoes, strawberries or peaches. Food colouring is sometimes added in addition to stabilizers. side dish in Indian cuisine made of dahi (yogurt, often referred to as curd) together with raw or cooked vegetables, more seldom fruit, or in the case of boondi raita, with fried droplets of batter made from besan (chickpea flour, generally labeled as gram flour).",
    process: [
      "To a mixer jar add mango flesh from 3-4 small alphonso mangoes.",
      "Blend it to a puree without adding water.",
      "Measure 2 cups of this mango pulp and transfer to a container.",
      "Add 1 cup sweetened condensed milk to it.",
      "Use a whisk and whisk well, should be well blended.",
      "The mixture will be slightly thick and creamy.",
      "To another mixing bowl add 1 cup frozen whipping cream.",
      "Start whipping using a hand blender. Use handwhisk too but it will take some time to whip else use a mixer jar with whipper blade.",
      "Keep whipping in medium speed until you start to see the cream turning foamy like this.",
      "Mildy stiff peaks is enough just as it is shown here in the below picture.",
      "Now add mango condensed milk mixture.",
      "Fold in gently.",
      "Mix until well combined.",
      "Pour into freezer safe containers. I used a regular plastic box with lid and my bread loaf tin.",
      "Place a butter paper over it, close with lid and freeze it for minimum 8 hrs.",
      "Now after 8 hrs remove the containers from fridge, rest for 5 mins atleast then remove the butter paper.",
      "Dip the icecream scooper in warm water.",
      "Then start scooping. If it is too hard wait for 2 more mins then scoop.",
      "First it may feel hard later after starting to scoop you will feel the creaminess.",
      "Yummy Mango Ice Cream is ready.",
    ],
    ingridients: [
      "2 Cups Curd",
      "3 tsp Boiled Beetroot",
      "1 tsp Cucumber",
      "1/2 small Onion",
      "1/2 tsp Salt",
      "2 tsp Coriander Leaves",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/12.jpg",
  },
];
