export const data_dessert = [
  {
    id: 2,
    title: "Mango Peda",
    desc: "'Mango Peda', a flavorful and delicious Indian sweet / dessert. The mango mania now continues with one more Indian dessert rich with the flavor of mangoes. This time around it is in the form of a Mango Peda, which is sweet, chewy and yet dissolves in your mouth just like a good old Indian sweet.",
    process: [
      "firstly, in a large kadai heat 2 tbsp ghee, ¼ cup milk, few thread saffron and 1 cup mango pulp.",
      "stir well making sure everything is well combined.",
      "now add ¼ cup sugar and stir until sugar dissolves completely.",
      "further, add 1 cup milk powder and ¼ cup cashew powder.",
      "mix well making sure the mixture is well combined.",
      "mash well making sure there are no lumps present.",
      "keeping the flame on low, stir continuously. the mixture thickens after 5 minutes.",
      "further, add ¼ tsp cardamom powder and mix well.",
      "and after 15 minutes, the mixture starts to separate the pan and holds shape. do not overcook as the peda hardens.",
      "transfer the prepared mixture into a greased plate and spread uniformly.",
      "cool for 5 minutes, and start preparing ball-sized peda.",
      "design using the flower mould. you can also decorate using a toothpick or fork.",
      "finally, serve mango peda for a week when stored in an airtight container.",
    ],
    ingridients: [
      "2 tbsp ghee / clarified butter",
      "¼ cup milk",
      "few thread saffron / kesar",
      "1 cup mango pulp",
      "¼ cup sugar",
      "1 cup milk powder (unsweetened)",
      "¼ cup cashew powder",
      "¼ tsp cardamom powder",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/2.jpg",
  },

  {
    id: 9,
    title: "Beetroot Raita",
    desc: "Raita is a side dish in Indian cuisine made of dahi (yogurt, often referred to as curd) together with raw or cooked vegetables, more seldom fruit, or in the case of boondi raita, with fried droplets of batter made from besan (chickpea flour, generally labeled as gram flour).",
    process: [
      "Take some curd in a bowl.",
      "Add boiled beetroot to it.",
      "Blend them well together.",
      "Now, pour it in a bowl and add chopped cucumber and finely cut onions on top of it.",
      "Add salt and stir well.",
      "Garnish with coriander leaves.",
      "Best paired with Biryani or some other dishes.",
    ],
    ingridients: [
      "2 Cups Curd",
      "3 tsp Boiled Beetroot",
      "1 tsp Cucumber",
      "1/2 small Onion",
      "1/2 tsp Salt",
      "2 tsp Coriander Leaves",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/9.jpg",
  },

  {
    id: 11,
    title: "White Choco Cubes",
    desc: "The creation of the first modern chocolate bar is credited to Joseph Fry, who in 1847 discovered that he could make a moldable chocolate paste by adding melted cacao butter back into Dutch cocoa. By 1868, a little company called Cadbury was marketing boxes of chocolate candies in England.",
    process: [
      "First take the White Chocolate(crushed) into a bowl and microwave for 30 secs. After 30 secs take it out and stir with a dry spoon. Then again microwave for 30secs. After that add 1/2tsp of butter and mix it well.",
      "Rest for the chocolate compound for 4 mins in room temperature. Mix some pesta as well.",
      "Add the white chocolate in the mold and freeze for 2 mins.",
      "Now your cute little White Choco Cubes is ready to be served.",
    ],
    ingridients: [
      "200gm White Chocolate Compound",
      "1/2tsp Unsalted Butter",
      "Few crushed pesta",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/11.jpg",
  },

  {
    id: 12,
    title: "Mango Ice-cream",
    desc: "Raita is aIce cream is a frozen dessert typically made from milk or cream that has been flavoured with a sweetener, either sugar or an alternative, and a spice, such as cocoa or vanilla, or with fruit, such as mangoes, strawberries or peaches. Food colouring is sometimes added in addition to stabilizers. side dish in Indian cuisine made of dahi (yogurt, often referred to as curd) together with raw or cooked vegetables, more seldom fruit, or in the case of boondi raita, with fried droplets of batter made from besan (chickpea flour, generally labeled as gram flour).",
    process: [
      "To a mixer jar add mango flesh from 3-4 small alphonso mangoes.",
      "Blend it to a puree without adding water.",
      "Measure 2 cups of this mango pulp and transfer to a container.",
      "Add 1 cup sweetened condensed milk to it.",
      "Use a whisk and whisk well, should be well blended.",
      "The mixture will be slightly thick and creamy.",
      "To another mixing bowl add 1 cup frozen whipping cream.",
      "Start whipping using a hand blender. Use handwhisk too but it will take some time to whip else use a mixer jar with whipper blade.",
      "Keep whipping in medium speed until you start to see the cream turning foamy like this.",
      "Mildy stiff peaks is enough just as it is shown here in the below picture.",
      "Now add mango condensed milk mixture.",
      "Fold in gently.",
      "Mix until well combined.",
      "Pour into freezer safe containers. I used a regular plastic box with lid and my bread loaf tin.",
      "Place a butter paper over it, close with lid and freeze it for minimum 8 hrs.",
      "Now after 8 hrs remove the containers from fridge, rest for 5 mins atleast then remove the butter paper.",
      "Dip the icecream scooper in warm water.",
      "Then start scooping. If it is too hard wait for 2 more mins then scoop.",
      "First it may feel hard later after starting to scoop you will feel the creaminess.",
      "Yummy Mango Ice Cream is ready.",
    ],
    ingridients: [
      "2 Cups Curd",
      "3 tsp Boiled Beetroot",
      "1 tsp Cucumber",
      "1/2 small Onion",
      "1/2 tsp Salt",
      "2 tsp Coriander Leaves",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/12.jpg",
  },

  {
    id: 16,
    title: "Double Choco Modak",
    desc: "The origin of Modak is thought to have originated in the state of Maharashtra. Modak is known by many names throughout Indiaviz…mothagam or kozhukattai in Tamil, modhaka or kadubu in Kannada, and kudumu in Telugu, state-wise. In Japan, kangidan, a sweet similar to Modak, is presented to God Kangiten, the Japanese equivalent of Lord Ganesh. Kangidans are a type of dessert made with curds, honey, and red bean paste. They are deep fried after being wrapped in kneaded dough made from parched flour and shaped like a bun.",
    process: [
      "First take the Dark Chocolate(crushed) into a bowl and microwave for 30 secs. After 30 secs take it out and stir with a dry spoon. Then again microwave for 30secs. After that add 1/2tsp of butter and mix it well.",
      "Repeat the same process for white chocolate. After microwaving add some cashew nuts and pesta in the white chocolate and mix it well.",
      "Rest for the chocolate compound for 4 mins in room temperature.",
      "Add the white chocolate in the mold(modak mold) and cover it upto 1/3rd of the mold. Freeze for 2 mins and then add the dark chocolate upto the remaining height in the mold and freeze for another 2 mins.",
      "Now your Double Choco Modak is ready to be served.",
    ],
    ingridients: [
      "200gm White Chocolate",
      "100gm Dark Chocolate",
      "50gm Cashew Nuts (Grounded)",
      "50gm Pesta",
      "1tsp Unsalted Butter",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/16.jpg",
  },

  {
    id: 17,
    title: "Mango Kesari Phirni",
    desc: "Despite the dearth of evidence, it is believed that phirni hailed from ancient Persia or Middle East and it’s the Mughals who both invented and introduced it to India. The Mughal Empire relished the regal milk-based dish and made it popular. It is also backed by studies which say that the rich, milky, nutty and aromatic rice pudding in earthen bowls is a Mughal legacy. It was found that in Persia where Phirini is believed to have originated used the creamy rice pudding as the food of angels and was known as Sheer Birinj. It was first offered to Prophet Muhammad when he soared to 7th floor of heaven to meet God.",
    process: [
      "Firstly, soak 2 tbsp of basmati rice for 30 minutes.",
      "Discard the water and blend rice to coarse paste. Keep aside.",
      "Now in a large kadai boil 1 litre milk.",
      "Stir occasionally, and simmer for 10 minutes.",
      "Keep the flame on low or till milk thickens.",
      "Now add in prepared coarse rice paste.",
      "Stir continuously for 5 minutes else, lumps might form.",
      "Simmer for another 5 minutes stirring in between.",
      "Boil the milk till the rice gets cooked completely.",
      "Further add ¼ cup of sugar and 2 tbsp saffron milk.",
      "Mix well till the milk thickens and turn creamy.",
      "Add in cardamom powder and serve chilled garnished with chopped nuts.",
      "If looking to prepare mango phirni, allow the phirni to cool completely.",
      "Now add in ½ cup mango pulp and mix well. add more pulp depending on the sweetness.",
      "Finally, serve chilled mango phirni garnished with mango pulp, few chopped nuts, kesar and dry rose petals",
      "Delicious Mango kesari Phirni is ready to be served.",
    ],
    ingridients: [
      "2 tbsp basmati rice",
      "Water for soaking",
      "1 litre milk (full cream)",
      "¼ cup sugar",
      "¼ tsp cardamom powder / elachi powder",
      "2 tbsp saffron milk",
      "1 cup mango pulp",
      "Kesar, pesta(chopped)",
      "Rose Petals for garnishing.",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/17.jpg",
  },

  {
    id: 18,
    title: "Sujir Mohanbhog",
    desc: " Earlier according to some scholars, this dish was introduced to India by the Mughals, but the theory was discredited as it was already listed as shali-anna, present-day Kesari bat, in Manasollasa, a 12th-century work by a south Indian Chalukyan king, Someshvara III. In 14th-century Spain, semolina was cooked with almond milk, oil and optionally saffron for coloring. In India, sheera is made from semolina, ghee, and sugar; cardamom and milk, almonds and cashew-nuts are added.",
    process: [
      "In a pan mix together water, cardamom and sugar. Bring to a boil and stir till the sugar dissolves. Turn off the heat and keep.",
      "In a separate pan heat ghee and add suji. Cook on low heat till golden brown. Add the sugar syrup to the suji. Be careful as the suji will let off a lot of heat & steam when you add the syrup. Stir and cook the suji on medium heat till it thickens.",
      "Garnish with some grounded cashew nuts, dry rose petals and pesta",
      "Serve hot or cold as per your choice.",
    ],
    ingridients: [
      "Ghee – ⅔ cup",
      "Suji (semolina) – 1cup",
      "Water – 3cups",
      "Cardamom – 5no",
      "Sugar – ¾ cup",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/18.jpg",
  },
];
