export const data_nonveg = [
  {
    id: 1,
    title: "Kadai Chicken",
    desc: "Kadai chicken originated from Northern region of India where the winter is quite strong which is why the North-Indian dishes are usually loaded with heat and flavors from all the aromatic spices or as they are called 'garam masala' i.e. 'hot spices'. Once a Nepali guy liked it so much that he requested the recipe for it. So I sent him the recipe and thus began my new friendship.",
    process: [
      "Cut the tomatoes. Crush garlic & ginger coarsely.",
      "Heat oil in the pan, saute some cloves, bay leaves, cinnamon, cumin seeds, green chillies.",
      "Add chicken & mix well. Now add green cardamom powder and black pepper. Mix well. After a few minutes add 1/2 cup of warm water. Then put the tomatoes on top & cover the pan. Cook for few minutes, till the tomatoes are pulpy.",
      "Remove the skin of the tomatoes & mash them. Add garlic, ginger and saute them for a few minutes.",
      "Now add garam masala powder, red chilli powder, turmeric powder, coriander powder & yogurt. Mix well. Now cover it again and let it boil for 2-3 minutes.",
      "Mix chopped coriender leaves and let it rest for about 5 minutes.",
      "Best served with Naan / Paratha.",
    ],
    ingridients: [
      "Chicken - 750gm",
      "Tomatoes - 4pc",
      "Garlic Cloves - 15-20",
      "Ginger - 1 inch",
      "Cloves - 3-4",
      "Bay Leaves - 2",
      "Cinnamon - 1 inch",
      "Cumin Seeds - 1 tbsp",
      "Chopped Green Chillies - 2-3",
      "Green Cardamom Powder - 1/4 tsp",
      "Oil - 4-5 tbsp",
      "Yogurt - 3/4 cup",
      "Red Chilli Powder - 1 tsp",
      "Turmeric Powder - 1/4 tsp",
      "Garam Masala - 1 tsp",
      "Chopped Fresh Coriander - 1/4 cup",
      "Black Pepper to taste",
      "Salt to taste",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/food-lab-pics/main/1.jpg",
  },

  {
    id: 4,
    title: "Chicken Fetucine Alfredo",
    desc: "Fettuccine Alfredo is an Italian pasta dish of fresh fettuccine tossed with butter and Parmesan cheese (Italian: pasta al burro e parmigiano). As the cheese melts, it emulsifies the liquids to form a smooth and rich cheese sauce coating the pasta. The dish is named after Alfredo Di Lelio, who featured the dish at his restaurant in Rome in the early to mid-20th century; the 'ceremony' of preparing it tableside was an integral part of the dish.",
    process: [
      "Set a pot of water to boil.",
      "Brush Chicken with olive oil and season with 1 tsp salt, pepper, garlic powder on both sides.",
      "On medium heat in a pan drizzle t tbsp of ooil and butter.",
      "Sear Chicken for 3-6 minutes on each side until golden brown.",
      "For the sauce melt 1/2 cup of butter.",
      "When butter is melted add 2 tbsp of cream cheese.",
      "When the mixture has softyen pour 1/2 cup heavy cream.",
      "Season with 1 tsp salt, pepper and garlic powder and simmer on low heat for 15 minutes.",
      "While sauce simmers add pasta and salt to boiling water.",
      "Remove sauce from heat stir and add parmesan cheese.",
      "Toss all ingredients well and serve.",
      "Garnish with some grated cheese and chopped parsley.",
    ],
    ingridients: [
      "Fettucine Pasta",
      "Chicken (cut into small pieces) - 200gm",
      "Butter - 2 tbsp",
      "Cheese",
      "Parmesan Cheese - 1 and a 1/2 cup",
      "Heavy Cream 2 cup",
      "Salt - 1 tsp",
      "Pepper - 1 tsp",
      "Garlic Powder - 2 tsp",
      "Milk - 3/4 cup",
      "Pasta Masala - 1 pinch",
      "Chilli Flakes - 1 pinch",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/food-lab-pics/main/4.jpg",
  },

  {
    id: 6,
    title: "Tandoori Chicken",
    desc: "Dishes similar to tandoori chicken may have existed during the Harappan civilization during the Bronze Age of India. According to the archeologist Professor Vasant Shinde, the earliest evidence for a dish similar to tandoori chicken can be found in the Harappan civilization and dates back to 3000 BC. His team has found ancient ovens at Harappan sites which are similar to the tandoors that are used in the state of Punjab.",
    process: [
      "Make ½ cm deep cuts in the chicken surface. ",
      "Rub with 1 tsp salt, 1 tbsp lemon juice and 1 tsp red chili powder and set aside for 20 minutes.",
      "      Meanwhile heat mustard oil till lukewarm.",
      " Add the remaining red chili powder and blend well. Add all the remaining ingredients and mix well. You may add red colour or not, it is optional.",
      "Squeeze out all the moisture from the chicken and rub well with the prepared marinade.",
      "Marinate the chicken for 6-7 hours in the refrigerator.",
      "Remove the chicken from the refrigerator. Keep a live burning coal in a bowl and keep it in the middle of the chicken. Pour 1 tbsp mustard oil over it and cover immediately. Secure tightly so that no smoke escapes. Allow the smoke to settle down and rest for 15 minutes.",
      "Heat a large pan till very hot. Keep the chicken pieces over it and sear the chicken. When it colours on the underside, flip and cook on the other side too.",
      "Place a wire grill over the gas stove flame and place the cooked chicken pieces over it. Allow to char a bit. Baste with melted butter and flip. Cook till the chicken is done. Remove and serve with chutney, lemon wedges and onion rings.",
    ],
    ingridients: [
      "800g Chicken",
      "250 ml hung yoghurt",
      "1 tsp roasted cumin powder",
      "1 tbsp garlic paste",
      "1 tbsp ginger paste",
      "2 tbsp mustard (sarson) oil",
      "2 tbsp fresh lime juice",
      "Salt to taste",
      "¼ tsp turmeric powder",
      "1 tsp garam masala",
      "1 tsp black pepper",
      "1 tsp finely chopped green chilies",
      "2 tbsp Kashmiri red chili powder",
      "Butter to baste",
      "a pinch of orange red (tandoori) colour",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/6.jpg",
  },

  {
    id: 7,
    title: "Mocha Chingri",
    desc: "This Bengali delicacy makes use of a marvelous vegetable - the banana flower, known as 'mocha' in Bengali. Cooked with shrimps and coconut, it is best served with rice on the side.",
    process: [
      "Soak the chopped banana blossom in salted water along with a pinch of turmeric powder and juice of 1/2 lime for an hour.",
      "Marinate the prawns with a pinch of salt, turmeric powder and red chilli powder for 10 minutes.",
      "Wash the soaked banana blossom well and drain. Pressure cook in required quantity of water in which a pinch each of salt and turmeric powder has been added. Drain and mash well. Keep aside.",
      "Heat oil in a pan and fry the potatoes till light brown. Drain and keep aside. Fry the marinated prawns till they changes colour and keep aside.",
      "Temper the same oil with dry red chilies, bay leaves, cumin seeds, cinnamon, cloves and cardamoms.",
      "Add the onion and saute till light brown.",
      "Then add the ginger-garlic paste & all the dry spices (except garam masala and salt) mixed with some water. Saute till the oil separates.",
      "Add the chopped tomatoes and stir fry till it is mashed.",
      "Add the fried potatoes & prawns. Mix nicely and cook on a low flame for 2-3 minutes.",
      "Add the boiled mocha (banana flower), salt & green chilies. Give it a stir and cook, covered on a low flame till done. Sprinkle water at intervals if needed.",
      "When done, add the garam masala & ghee. Give it a toss and switch off the flame.",
      "Serve with hot steamed rice or chapati.",
    ],
    ingridients: [
      "1 medium size mocha / banana blossom, cleaned & chopped finely",
      "10-15 prawns, deveined & washed",
      "3 tbsp mustard oil",
      "2 bay leaves",
      "2 whole dry red chilies",
      "1 cinnamon stick",
      "2-3 green cardamoms",
      "4-5 cloves",
      "1 tsp cumin seeds",
      "1 potato, cubed",
      "1 onion, chopped",
      "1 tsp ginger-garlic paste",
      "1 tomato, chopped",
      "2-3 green chilies, slit to taste salt",
      "1/2 tsp turmeric powder",
      "1 tsp sugar (opt)",
      "1 tbsp coriander-cumin powder",
      "1 tsp garam masala powder",
      "1 tsp ghee",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/7.jpg",
  },

  {
    id: 8,
    title: "Chicken Biryani",
    desc: " Indian restaurateur Kris Dhillon believes that the dish originated in Persia, and was brought to India by the Mughals. Another theory claims that the dish was prepared in India before the first Mughal emperor Babur conquered India.",
    process: [
      "Powder the special garam masala powde",
      "Start by marinating the chicken with all the ingredients given. Let it marinate for 2 hours but overnight is grea",
      "Wash and soak basmati rice for a hou",
      "      Bring lots of water with salt to a boil. Once it boils, add in the drained rice and cook it for 5 to 7 mins till it is 90 percent done. When you taste it, it should have a bite.Drain it and set asid",
      "      Heat oil in a big pot which you are making biryan",
      "      Add in onions and fry till golden, drain and set asid",
      "      Soak saffron in some warm milk, heat ghee in a sauce pan and fry cashews and raisans till golde",
      "      In the same oil add in chicken and mix well for 5 min",
      "      Now layer the rice over it, top with fried onions, chopped herbs, saffron milk, fried nuts along with the ghee, kewra and rose essence. Cover the entire pot with foil and cover with a plate. Place a weight over it and let it cook on a very very low flame for 30 to 35 min",
      "      Now remove the weight and foil and fluff the rice carefull",
      "      Serve wih some raita.",
    ],
    ingridients: [
      "1 kg Basmati Rice",
      "¾ cup Oil",
      "1.5 kg Chicken",
      "3 large Onion sliced thinly",
      "a pinch Saffron a pinch",
      "¼ cup Warm Milk",
      "¼ cup Coriander leaves finely chopped",
      "¼ cup Mint Leaves finely chopped",
      "3 tbsp Ghee",
      "50 grams Cashews",
      "50 grams Kishmish",
      "Kewra Essence few drops",
      "Rose Essence few drops",
      "Salt to taste",
      "or Marination",
      "2 tbsp Chilli Powder",
      "3 tbsp Coriander Powder",
      "Salt to taste",
      "½ cup Coriander leaves chopped finely",
      "½ cup Mint Leaves chopped finely",
      "1½ cup Thick Unsour Curd",
      "4 Green Chillies",
      "3 tbsp Ginger Garlic Paste - 3 tblspn",
      "Special Garam Masala Powder (recipe below)",
      "1 tbsp Lemon Juice",
      "or Special Garam Masala Powder:",
      "10 piece Cloves",
      "10 piece Cardamom",
      "3 Bay Leaf",
      "5cm Cinnamon",
      "1 tbsp Cumin Seeds",
      "4 Black Stone Flower / Kal Paasi",
      "1 Star Anise",
      "1 tbsp Fennel Seeds",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/8.jpg",
  },
];
