export const data = [
  {
    id: 1,
    title: "Kadai Chicken",
    desc: "Kadai chicken originated from Northern region of India where the winter is quite strong which is why the North-Indian dishes are usually loaded with heat and flavors from all the aromatic spices or as they are called 'garam masala' i.e. 'hot spices'. Once a Nepali guy liked it so much that he requested the recipe for it. So I sent him the recipe and thus began my new friendship.",
    process: [
      "Cut the tomatoes. Crush garlic & ginger coarsely.",
      "Heat oil in the pan, saute some cloves, bay leaves, cinnamon, cumin seeds, green chillies.",
      "Add chicken & mix well. Now add green cardamom powder and black pepper. Mix well. After a few minutes add 1/2 cup of warm water. Then put the tomatoes on top & cover the pan. Cook for few minutes, till the tomatoes are pulpy.",
      "Remove the skin of the tomatoes & mash them. Add garlic, ginger and saute them for a few minutes.",
      "Now add garam masala powder, red chilli powder, turmeric powder, coriander powder & yogurt. Mix well. Now cover it again and let it boil for 2-3 minutes.",
      "Mix chopped coriender leaves and let it rest for about 5 minutes.",
      "Best served with Naan / Paratha.",
    ],
    ingridients: [
      "Chicken - 750gm",
      "Tomatoes - 4pc",
      "Garlic Cloves - 15-20",
      "Ginger - 1 inch",
      "Cloves - 3-4",
      "Bay Leaves - 2",
      "Cinnamon - 1 inch",
      "Cumin Seeds - 1 tbsp",
      "Chopped Green Chillies - 2-3",
      "Green Cardamom Powder - 1/4 tsp",
      "Oil - 4-5 tbsp",
      "Yogurt - 3/4 cup",
      "Red Chilli Powder - 1 tsp",
      "Turmeric Powder - 1/4 tsp",
      "Garam Masala - 1 tsp",
      "Chopped Fresh Coriander - 1/4 cup",
      "Black Pepper to taste",
      "Salt to taste",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/1.jpg",
  },

  {
    id: 2,
    title: "Mango Peda",
    desc: "",
    process: ["Step 1", "Step 2"],
    ingridients: ["Step 1", "Step 2"],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/2.jpg",
  },

  {
    id: 3,
    title: "Red Velvet Cake",
    desc: "In the 19th century, 'velvet' cake, a soft and velvety crumb cake, came to be served as a fancy dessert, in contrast to what had been the more common, coarser-crumbed cake. Around the turn of the 20th century, devil's food cake was introduced, which is how some believe that red velvet cake came about.",
    process: ["Step 1", "Step 2"],
    ingridients: ["Step 1", "Step 2"],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/3.jpg",
  },

  {
    id: 4,
    title: "Chicken Fetucine Alfredo",
    desc: "Fettuccine Alfredo is an Italian pasta dish of fresh fettuccine tossed with butter and Parmesan cheese (Italian: pasta al burro e parmigiano). As the cheese melts, it emulsifies the liquids to form a smooth and rich cheese sauce coating the pasta. The dish is named after Alfredo Di Lelio, who featured the dish at his restaurant in Rome in the early to mid-20th century; the 'ceremony' of preparing it tableside was an integral part of the dish.",
    process: [
      "Set a pot of water to boil.",
      "Brush Chicken with olive oil and season with 1 tsp salt, pepper, garlic powder on both sides.",
      "On medium heat in a pan drizzle t tbsp of ooil and butter.",
      "Sear Chicken for 3-6 minutes on each side until golden brown.",
      "For the sauce melt 1/2 cup of butter.",
      "When butter is melted add 2 tbsp of cream cheese.",
      "When the mixture has softyen pour 1/2 cup heavy cream.",
      "Season with 1 tsp salt, pepper and garlic powder and simmer on low heat for 15 minutes.",
      "While sauce simmers add pasta and salt to boiling water.",
      "Remove sauce from heat stir and add parmesan cheese.",
      "Toss all ingredients well and serve.",
      "Garnish with some grated cheese and chopped parsley.",
    ],
    ingridients: [
      "Fettucine Pasta",
      "Chicken (cut into small pieces) - 200gm",
      "Butter - 2 tbsp",
      "Cheese",
      "Parmesan Cheese - 1 and a 1/2 cup",
      "Heavy Cream 2 cup",
      "Salt - 1 tsp",
      "Pepper - 1 tsp",
      "Garlic Powder - 2 tsp",
      "Milk - 3/4 cup",
      "Pasta Masala - 1 pinch",
      "Chilli Flakes - 1 pinch",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/4.jpg",
  },

  {
    id: 5,
    title: "Red Velvet Cupcake",
    desc: "During WWII soldiers and civilians had to ration off food and supplies. Baking products like sugar and butter were a part of the rations. As a result, some bakers chose to use beet juice in their cakes.You can still find red velvet cake recipes today that call for beet juice. The red color of the beets makes the cake have a more delicious appeal. However, not only do the beets make the cake pretty, but they also make the cake soft.",
    process: [
      "Start off by preheating the oven to 160 °C (320°F) with the fan on. If your oven doesn't have a fan option, then you will need to increase the baking temperature to 175°C (347°F).",
      "Line up the cupcake tray with cupcake liners",
      "For our cupcakes start off by putting 1¼ cupsof all purpose flour, 1½ tbsp cornflour, 1½ tbsp cocoa powder, ¼ tsp baking soda, ½ tsp baking powder, ¼ tsp salt. Use a whisk to combine them together.",
      "Set this aside and on another bowl add 3tbsp of unsalted butter, ⅓ cup vegetable oil, 1 cup white sugar. Using the blender blend all of the ingredients together until its light and creamy. Then add 2 eggs one at atime mixing well in between each addition.",
      "Then add ½ tbsp vanilla essence/extract, ¾ tsp white vinegar, 1¾ tbsp red liquid food colour. Then add the dry ingredients from the other bowl and add ⅓ cup buttermilk and mix them together",
      "Distribute it evenly in the cupcake tray and bake them until fluffy",
      "For the cheese frosting add ½ cup of unsalted butter, 2¼ cups icing sugar in 2-3 batches, ¾ cup cream cheese, ¾ tsp vanilla essence/extract, ¾ tbsp lemon juice and mix them.",
      "Now use this frosting to swirl around thew cupcake. So, we have ourselves Sarmi's style red velvet cupcakes.",
    ],
    ingridients: [
      "1¼ cups regular all-purpose flour",
      "1½ tbsp cornflour",
      "1½ tbsp unsweetened cocoa powder",
      "¼ tsp baking soda",
      "½ tsp baking powder",
      "¼ tsp salt - omit if using salted butter",
      "3 tbsp unsalted butter",
      "⅓ cup unflavoured vegetable oil",
      "1 cup white sugar",
      "2 large eggs - room temperature",
      "½ tbsp vanilla essence/extract",
      "¾ tsp white vinegar",
      "1¾ tbsp red liquid food colour",
      "⅓ cup buttermilk",
      "-- Cream Cheese Buttercream --",
      "½ cup unsalted butter",
      "2¼ cups icing sugar",
      "¾ cup cream cheese",
      "¾ tsp vanilla essence/extract",
      "¾ tbsp lemon juice",
    ],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/5.jpg",
  },

  {
    id: 6,
    title: "Tandoori Chicken",
    desc: "lorem safasf safsafsafsaf f af safas ac asc c ac asc",
    process: ["Step 1", "Step 2"],
    ingridients: ["Step 1", "Step 2"],
    image:
      "https://raw.githubusercontent.com/samrat-ganguly/sarmis-food-lab-pics/main/6.jpg",
  },

  {
    id: 7,
    title: "B",
    desc: "lorem safasf safsafsafsaf f af safas ac asc c ac asc",
    process: ["Step 1", "Step 2"],
    ingridients: ["Step 1", "Step 2"],
    image:
      "https://plus.unsplash.com/premium_photo-1663844169693-9b0eb5032423?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw3fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 8,
    title: "D",
    desc: "lorem safasf safsafsafsaf f af safas ac asc c ac asc",
    process: ["Step 1", "Step 2"],
    ingridients: ["Step 1", "Step 2"],
    image:
      "https://images.unsplash.com/photo-1678357437275-a4016d7faafd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw0NXx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 9,
    title: "E",
    desc: "lorem safasf safsafsafsaf f af safas ac asc c ac asc",
    process: ["Step 1", "Step 2"],
    ingridients: ["Step 1", "Step 2"],
    image:
      "https://plus.unsplash.com/premium_photo-1663844169693-9b0eb5032423?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw3fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 10,
    title: "E A",
    desc: "lorem safasf safsafsafsaf f af safas ac asc c ac asc",
    process: ["Step 1", "Step 2"],
    ingridients: ["Step 1", "Step 2"],
    image:
      "https://plus.unsplash.com/premium_photo-1663844169693-9b0eb5032423?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw3fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 11,
    title: "D",
    desc: "lorem safasf safsafsafsaf f af safas ac asc c ac asc",
    process: ["Step 1", "Step 2"],
    ingridients: ["Step 1", "Step 2"],
    image:
      "https://plus.unsplash.com/premium_photo-1663844169693-9b0eb5032423?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw3fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 12,
    title: "E b a",
    desc: "lorem safasf safsafsafsaf f af safas ac asc c ac asc",
    process: ["Step 1", "Step 2"],
    ingridients: ["Step 1", "Step 2"],
    image:
      "https://plus.unsplash.com/premium_photo-1663844169693-9b0eb5032423?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw3fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 13,
    title: "A",
    desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    process: ["Step 1", "Step 2"],
    ingridients: ["Step 1", "Step 2"],
    image:
      "https://images.unsplash.com/photo-1678297405555-c2816eccdd00?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw5fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 14,
    title: "A",
    desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    process: ["Step 1", "Step 2"],
    ingridients: ["Step 1", "Step 2"],
    image:
      "https://images.unsplash.com/photo-1678304358381-36c60e345c14?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxMHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 15,
    title: "A",
    desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    process: ["Step 1", "Step 2"],
    ingridients: ["Step 1", "Step 2"],
    image:
      "https://images.unsplash.com/photo-1678344066863-8fca6ce25767?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxMXx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60",
  },
  {
    id: 16,
    title: "A",
    desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    process: ["Step 1", "Step 2"],
    ingridients: ["Step 1", "Step 2"],
    image:
      "https://images.unsplash.com/photo-1678228987283-a82512afce73?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxNHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60",
  },
];
